### ISSUE TITLE
fix this error

### ISSUE THREAD

**Issue by josecuervo2016** [feross/run-waterfall#8]
[01:04:01] [Netty Worker IO Thread #5/ERROR]: [/97.107.128.125:50477|bQjHr5kQ7xfiiSEK] -> UpstreamBridge - encountered exception
java.lang.IllegalArgumentException: Chat message too long
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:137) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by josecuervo2016** [comment]
and other error
https://pastebin.com/mAt4n3z1

**Comment by josecuervo2016** [comment]
UpstreamBridge - encountered exception
java.lang.IllegalArgumentException: Chat message is empty
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:138) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [Waterfall-160.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:5660854:160]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
